apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mealie.fullname" . }}
  labels:
    {{- include "mealie.labels" . | nindent 4 }}
data:
  PUID: "1000"
  PGID: "1000"
  TZ: {{ .Values.mealie.timezone | quote }}
  MAX_WORKERS: {{ .Values.mealie.maxWorkers | quote }}
  WEB_CONCURRENCY: {{ .Values.mealie.webConcurrency | quote }}
  BASE_URL: {{ .Values.mealie.baseUrl | quote }}
  ALLOW_SIGNUP: {{ .Values.mealie.allowSignup | quote }}
  {{- with .Values.mealie.defaultGroup }}
  DEFAULT_GROUP: {{ . | quote }}
  {{- end }}
  {{- with .Values.mealie.defaultHousehold }}
  DEFAULT_HOUSEHOLD: {{ . | quote }}
  {{- end }}
  {{- if .Values.email.enabled }}
  SMTP_HOST: {{ .Values.email.host | quote }}
  SMTP_PORT: {{ .Values.email.port | quote }}
  SMTP_FROM_NAME: {{ .Values.email.fromName | quote }}
  SMTP_FROM_EMAIL: {{ .Values.email.fromEmail | quote }}
  SMTP_AUTH_STRATEGY: {{ .Values.email.authStrategy | quote }}
  {{- end }}
