apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mealie.fullname" . }}
  labels:
    {{- include "mealie.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_ENGINE: postgres
  {{- if .Values.postgresql.enabled }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password }}
  POSTGRES_SERVER: {{ include "mealie.postgresHost" . }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database }}
  {{- else }}
  POSTGRES_USER: {{ .Values.externalDatabase.user }}
  POSTGRES_PASSWORD: {{ .Values.externalDatabase.password }}
  POSTGRES_SERVER: {{ include "mealie.postgresHost" . }}
  POSTGRES_DB: {{ .Values.externalDatabase.database }}
  {{- end }}
  POSTGRES_PORT: "5432"
  {{- with .Values.mealie.secretKey }}
  SECRET_KEY: {{ . | quote }}
  {{- end }}
